[package]
name = "laspa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0", default-features = false }
regex = { version = "1.9.3", default-features = false }
